sudo: false
language: ruby
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_install: gem install bundler -v 1.16.1
script: bundle exec rspec